name: Xcode - Build and Analyze

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build and analyse default scheme using xcodebuild command
    runs-on: macos-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Download Fortify ScanCentral Client
        uses: fortify/gha-setup-scancentral-client@v2
      - name: Package Code + Dependencies
        run: scancentral package -bt none -o package.zip
        env:
          PACKAGE_OPTS: ""
      - name: Download Fortify on Demand Universal CI Tool
        uses: fortify/gha-setup-fod-uploader@v1
      - name: Perform SAST Scan
        run: java -jar $FOD_UPLOAD_JAR -z package.zip -aurl $FOD_API_URL -purl $FOD_URL -rid 9389 -tc "FOD_BSI" -ac "7423b1c5-1af7-4c39-8628-6f692ab48be2" "VUpVejZobzZFdXFGQ1VyMzNIbDQlb0Mua0Zve3dh0" $FOD_UPLOADER_OPTS
        env: 
          FOD_TENANT: ${{ secrets.FOD_TENANT }}  
          FOD_USER: ${{ secrets.FOD_USER }}
          FOD_PAT: ${{ secrets.FOD_PAT }}
          FOD_RELEASE_ID: ${{ secrets.FOD_RELEASE_ID }}
          FOD_URL: "https://sandbox.fortify.com/"
          FOD_API_URL: "https://api.sandbox.fortify.com/"
          FOD_UPLOADER_OPTS: "-ep 2 -pp 0 -rp 2"
          FOD_UPLOADER_NOTES: 'Triggered by GitHub Actions (${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})'
      
